name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  
  workflow_dispatch:


jobs:
  DEV:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and Test
        run: |
          # Perform the build and test process here

      - name: Deploy to Dev
        run: |
          # Deploy the application to the DEV environment

  QA:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and Test
        run: |
          # Perform the build and test process here

      - name: Deploy to QA
        run: |
          # Deploy the application to the QA environment

  PROD:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and Test
        run: |
          # Perform the build and test process here

      - name: Deploy to Prod
        run: |
          # Deploy the application to the Production environment
