name: UPDATE-AUTO

on:
  schedule:
    - cron: '* 21,8 * * *' # Chạy vào lúc  theo múi giờ UTC+7
  workflow_dispatch:

jobs:
  readmebot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Generate new SVG
        run: |
          touch .env
          echo WEATHER_API_KEY: ${{ secrets.WEATHER_API_KEY }} >> .env
          cat .env
          node ./generate-svg.js

      - name: Commit changes
        uses: EndBug/add-and-commit@v7
        with:
          author_name: Luong Tran
          author_email: luongtranstaff@gmail.com
          message: 'Auto update README.md'
          add: 'autochat.svg'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
